# key names
VMACONFIG = "VMACONFIG"
PARENT_SERVICE = "PARENT"
CHILD_SERVICE = "CHILD"
SERVICE_NAME = "SERVICE_NAME"
FB_CLIENT_ID = "FB_CLIENT_ID"
FB_CLIENT_SECRET = "FB_CLIENT_SECRET"
CLIENT_CERT = "CLIENT_CERT"

DEFAULT_CONFIG_FILE = "config.json"
SCHEMA_ROUTE = "/api/v1/internal/schema"
